version: '2'

services:
  app:
    image: 'wiszenkoigor/practice:restapipsql'
    #build:
    #  context: .
    container_name: app
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/testdb
      - spring.datasource.username=postgres
      - spring.datasource.password=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
    - 8080:8080

  db:
    image: 'moja-baza-psql'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass